wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.14
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      - 5
      - 9
      2:
      - 1
      - 5
      - 9
      3:
      - 1
      4: 3.8.5
      5: 0.10.14
      8:
      - 3
